//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiraAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JiraAPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JiraAPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JiraAPI.Properties.JiraAPI", typeof(JiraAPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachment to Issue.
        /// </summary>
        internal static string AddAttachment {
            get {
                return ResourceManager.GetString("AddAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment to Issue.
        /// </summary>
        internal static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key for Atlassian account..
        /// </summary>
        internal static string ApiKeyDesc {
            get {
                return ResourceManager.GetString("ApiKeyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path for attachment..
        /// </summary>
        internal static string AttachmentDesc {
            get {
                return ResourceManager.GetString("AttachmentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Path.
        /// </summary>
        internal static string AttachmentPath {
            get {
                return ResourceManager.GetString("AttachmentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment body..
        /// </summary>
        internal static string BodyDesc {
            get {
                return ResourceManager.GetString("BodyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Issue.
        /// </summary>
        internal static string CreateIssue {
            get {
                return ResourceManager.GetString("CreateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Issue.
        /// </summary>
        internal static string EditIssue {
            get {
                return ResourceManager.GetString("EditIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Extraction.
        /// </summary>
        internal static string FieldExtraction {
            get {
                return ResourceManager.GetString("FieldExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field JSON.
        /// </summary>
        internal static string FieldJson {
            get {
                return ResourceManager.GetString("FieldJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to JSON file with fields to extract from response. This will override default values..
        /// </summary>
        internal static string FieldJsonDesc {
            get {
                return ResourceManager.GetString("FieldJsonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field List.
        /// </summary>
        internal static string FieldList {
            get {
                return ResourceManager.GetString("FieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of fields to extract from response. If default values are being used, then the items in this list will be added on to the default values..
        /// </summary>
        internal static string FieldListDesc {
            get {
                return ResourceManager.GetString("FieldListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Issue.
        /// </summary>
        internal static string GetIssue {
            get {
                return ResourceManager.GetString("GetIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Key.
        /// </summary>
        internal static string IssueKey {
            get {
                return ResourceManager.GetString("IssueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key of target issue..
        /// </summary>
        internal static string IssueKeyDesc {
            get {
                return ResourceManager.GetString("IssueKeyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path for JSON file with issue data in it..
        /// </summary>
        internal static string JsonCreateDesc {
            get {
                return ResourceManager.GetString("JsonCreateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path for JSON file with updated issue data stored in it..
        /// </summary>
        internal static string JsonEditDesc {
            get {
                return ResourceManager.GetString("JsonEditDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON File Path.
        /// </summary>
        internal static string JsonFilePath {
            get {
                return ResourceManager.GetString("JsonFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue data returned as JSON string..
        /// </summary>
        internal static string ResultJsonDesc {
            get {
                return ResourceManager.GetString("ResultJsonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue key of the newly created issue..
        /// </summary>
        internal static string ResultKeyDesc {
            get {
                return ResourceManager.GetString("ResultKeyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full URL for target Jira site starting with http(s):// excluding the API endpoint..
        /// </summary>
        internal static string URLDesc {
            get {
                return ResourceManager.GetString("URLDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default.
        /// </summary>
        internal static string UseDefault {
            get {
                return ResourceManager.GetString("UseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean value to determine whether or not default field values (&quot;summary&quot;, &quot;description&quot;, &quot;status&quot;, &quot;priority&quot;, &quot;fixVersions&quot;, &quot;labels&quot;) should be used to extract fields from the response..
        /// </summary>
        internal static string UseDefaultDesc {
            get {
                return ResourceManager.GetString("UseDefaultDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username for Atlassian account..
        /// </summary>
        internal static string UsernameDesc {
            get {
                return ResourceManager.GetString("UsernameDesc", resourceCulture);
            }
        }
    }
}
